# ExcelSKU.py

EXCEL_SKU = {
    "Post-Bio-GH": "POST-BIO-GH",
    "Omega-Alg": "OMEGA-ALG",
    "Edi-DR-BC-SML": "DR-BC-SML",
    "Edi-DR-BC-LRG": "DR-BC-LRG",
    "TS-Edi-HJ-PB": "TS-HJ-PB",
    "Edi-HJ-PB-SML": "HJ-PB-SML",
    "Edi-HJ-PB-LRG": "HJ-PB-LRG",
    "Edi-HJ-PB-FAM": "HJ-PB-FAM",
    "TS-Edi-STRESS-PB": "TS-STRESS-PB",
    "Edi-STRESS-PB-SML": "STRESS -PB-SML",
    "Edi-STRESS-PB-LRG": "STRESS-PB-LRG",
    "Edi-STRESS-PB-FAM": "STRESS-PB-FAM",
    "Edi-DR-SP-SML": "DR-SP-SML",
    "Edi-DR-SP-LRG": "DR-SP-LRG",
    "TS-Edi-STRESS-Pepp": "TS-STRESS-PEPP",
    "Edi-STRESS-Pepp-SML": "STRESS-PEPP-SML",
    "Edi-STRESS-Pepp-LRG": "STRESS-PEPP-LRG",
    "100-DR-HO": "100-DR-HO",
    "200-DR-HO": "200-DR-HO",
    "500-DR-HO": "500-DR-HO",
    "750-DR-HO": "750-DR-HO",
    "150-Mini-Stress-HO": "150-SR-MINI",
    "300-SR-HO": "300-SR-HO",
    "600-SR-HO": "600-SR-HO",
    "300-HJR-HO": "300-HJR-HO",
    "600-HJR-HO": "600-HJR-HO",
    "180-CAT-SR": "CAT-180",
    "100-Lipe-Ultra": "100-LIPE-ULTRA",
    "300-Lipe-Ultra": "300-LIPE-ULTRA",
    "600-Lipe-Ultra": "600-LIPE-ULTRA",
    "CAP450": "450 CAP",
    "SNT30": "SNT30",
    "TS-Itchy-Dry-Shampoo": "TS-Itchy & Dry Shampoo",
    "Itchy & Dry-SK-CT": "ITCHY & DRY SK-CT",
    "Itchy-Dry-Shampoo-Gallon": "ITCHY-DRY SHAMPOO-GALLON",
    "Sensitive-SK-CT": "SENSITIVE SK-CT",
    "Conditioner-SK-CT": "CONDITIONER SK-CT",
    "TS-2in1-Shampoo": "TS-2 IN 1 SHAMPOO",
    "2in1-SK-CT": "2 IN 1 SK-CT",
    "SK-PW-RL": "SK-PW-RL",
}
